export const products = [
	{
		id: 1,
		name: "Margherita 23 cm",
		price: 25.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},

	{
		id: 2,
		name: "Margherita 32 cm",
		price: 37.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},

	{
		id: 3,
		name: "Margherita 42 cm",
		price: 49.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},

	// { id: 4, name: "Margherita 60 cm", price: 84.9, category: "Pizza", cm: 60 },
	{
		id: 5,
		name: "Funghi 23 cm",
		price: 30.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 6,
		name: "Funghi 32 cm",
		price: 41.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 7,
		name: "Funghi 42 cm",
		price: 55.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 8, name: "Funghi 60 cm", price: 88.9, category: "Pizza", cm: 60 },
	{
		id: 9,
		name: "Prosciutto 23 cm",
		price: 31.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 10,
		name: "Prosciutto 32 cm",
		price: 43.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 11,
		name: "Prosciutto 42 cm",
		price: 57.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 12, name: "Prosciutto 60 cm", price: 89.9, category: "Pizza", cm: 60 },
	{
		id: 13,
		name: "Capriciosa 23 cm",
		price: 32.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 14,
		name: "Capriciosa 32 cm",
		price: 44.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 15,
		name: "Capriciosa 42 cm",
		price: 58.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 16, name: "Capriciosa 60 cm", price: 90.9, category: "Pizza", cm: 60 },
	{
		id: 17,
		name: "Hawajska 23 cm",
		price: 32.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 18,
		name: " Hawajska 32 cm",
		price: 44.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 19,
		name: "Hawajska 42 cm",
		price: 58.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 20, name: "Hawajska 60 cm", price: 90.9, category: "Pizza", cm: 60 },
	{
		id: 21,
		name: "Salami 23 cm",
		price: 32.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 22,
		name: "Salami 32 cm",
		price: 44.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 23,
		name: "Salami 42 cm",
		price: 58.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 24, name: "Salami 60 cm", price: 90.9, category: "Pizza", cm: 60 },
	{
		id: 25,
		name: "Pepperoni 23 cm",
		price: 32.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 26,
		name: "Pepperoni 32 cm",
		price: 44.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 27,
		name: "Pepperoni 42 cm",
		price: 58.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 28, name: "Pepperoni 60 cm", price: 90.9, category: "Pizza", cm: 60 },
	{
		id: 29,
		name: "Chicken 23 cm",
		price: 33.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 30,
		name: "Chicken 32 cm",
		price: 45.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 31,
		name: "Chicken 42 cm",
		price: 59.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 32, name: "Chicken 60 cm", price: 93.9, category: "Pizza", cm: 60 },
	{
		id: 33,
		name: "Tosca 23 cm",
		price: 33.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 34,
		name: "Tosca 32 cm",
		price: 45.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 35,
		name: "Tosca 42 cm",
		price: 59.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 36, name: "Tosca 60 cm", price: 93.9, category: "Pizza", cm: 60 },
	{
		id: 37,
		name: "Chłopska 23 cm",
		price: 35.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 38,
		name: "Chłopska 32 cm",
		price: 46.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 39,
		name: "Chłopska 42 cm",
		price: 60.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 40, name: "Chłopska 60 cm", price: 94.9, category: "Pizza", cm: 60 },
	{
		id: 41,
		name: "Diablo 23 cm",
		price: 35.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 42,
		name: "Diablo 32 cm",
		price: 46.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 43,
		name: "Diablo 42 cm",
		price: 60.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 44, name: "Diablo 60 cm", price: 94.9, category: "Pizza", cm: 60 },
	{
		id: 45,
		name: "Torino 23 cm",
		price: 33.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 46,
		name: "Torino 32 cm",
		price: 45.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 47,
		name: "Torino 42 cm",
		price: 59.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 48, name: "Torino 60 cm", price: 92.9, category: "Pizza", cm: 60 },
	{
		id: 49,
		name: "Swojska 23 cm",
		price: 35.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 50,
		name: "Swojska 32 cm",
		price: 47.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 51,
		name: "Swojska 42 cm",
		price: 61.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 52, name: "Swojska 60 cm", price: 94.9, category: "Pizza", cm: 60 },
	{
		id: 53,
		name: "Rimini 23 cm",
		price: 35.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 54,
		name: "Rimini 32 cm",
		price: 47.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 55,
		name: "Rimini 42 cm",
		price: 61.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 56, name: "Rimini 60 cm", price: 94.9, category: "Pizza", cm: 60 },
	{
		id: 57,
		name: "Italiana 23 cm",
		price: 35.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 58,
		name: "Italiana 32 cm",
		price: 47.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 59,
		name: "Italiana 42 cm",
		price: 61.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 60, name: "Italiana 60 cm", price: 94.9, category: "Pizza", cm: 60 },
	{
		id: 61,
		name: "Pizza Spianata e Gorgonzola 23 cm",
		price: 35.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 62,
		name: "Pizza Spianata e Gorgonzola 32 cm",
		price: 47.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 63,
		name: "Pizza Spianata e Gorgonzola 42 cm",
		price: 61.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 64,
	// 	name: "Pizza Spianata e Gorgonzola 60 cm",
	// 	price: 95.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 65,
		name: "Bella 23 cm",
		price: 36.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 66,
		name: "Bella 32 cm",
		price: 48.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 67,
		name: "Bella 42 cm",
		price: 62.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 68, name: "Bella 60 cm", price: 95.9, category: "Pizza", cm: 60 },
	{
		id: 69,
		name: "Góralska 23 cm",
		price: 36.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 70,
		name: "Góralska 32 cm",
		price: 48.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 71,
		name: "Góralska 42 cm",
		price: 62.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 72, name: "Góralska 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 73,
		name: "London 23 cm",
		price: 36.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 74,
		name: "London 32 cm",
		price: 48.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 75,
		name: "London 42 cm",
		price: 62.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 76, name: "London 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 77,
		name: "Siciliana 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 78,
		name: "Siciliana 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 79,
		name: "Siciliana 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 80, name: "Siciliana 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 81,
		name: "Piracka 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 82,
		name: "Piracka 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 83,
		name: "Piracka 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 84, name: "Piracka 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 85,
		name: "Grecka 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 86,
		name: "Grecka 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 87,
		name: "Grecka 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 88, name: "Grecka 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 89,
		name: "Fiore 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 90,
		name: "Fiore 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 91,
		name: "Fiore 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 92, name: "Fiore 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 93,
		name: "Cosa Nostra 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 94,
		name: "Cosa Nostra 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 95,
		name: "Cosa Nostra 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 96, name: "Cosa Nostra 60 cm", price: 96.9, category: "Pizza", cm: 60 },
	{
		id: 97,
		name: "Palermo 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 98,
		name: "Palermo 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 99,
		name: "Palermo 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 100, name: "Palermo 60 cm", price: 97.9, category: "Pizza", cm: 60 },
	{
		id: 101,
		name: "Vegetariana 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 102,
		name: "Vegetariana 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 103,
		name: "Vegetariana 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 104,
	// 	name: "Vegetariana 60 cm",
	// 	price: 97.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 105,
		name: "Frutti di Mare 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 106,
		name: "Frutti di Mare 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 107,
		name: "Frutti di Mare 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 108,
	// 	name: "Frutti di Mare 60 cm",
	// 	price: 98.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 109,
		name: "4 Sery 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 110,
		name: "4 Sery 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 111,
		name: "4 Sery 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 112, name: "4 Sery 60 cm", price: 98.9, category: "Pizza", cm: 60 },
	{
		id: 113,
		name: "Molto Picante 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 114,
		name: "Molto Picante 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 115,
		name: "Molto Picante 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 116,
	// 	name: "Molto Picante 60 cm",
	// 	price: 98.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 113,
		name: "Chorizo 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 280,
		name: "Chorizo 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 281,
		name: "Chorizo 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 282,
	// 	name: "Chorizo 60 cm",
	// 	price: 98.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 117,
		name: "Uczta Mięsna 23 cm",
		price: 38.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 118,
		name: "Uczta Mięsna 32 cm",
		price: 50.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 119,
		name: "Uczta Mięsna 42 cm",
		price: 64.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 120,
	// 	name: "Uczta Mięsna 60 cm",
	// 	price: 99.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 121,
		name: "Mafiosa 23 cm",
		price: 38.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 122,
		name: "Mafiosa 32 cm",
		price: 50.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 123,
		name: "Mafiosa 42 cm",
		price: 64.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 124, name: "Mafiosa 60 cm", price: 99.9, category: "Pizza", cm: 60 },
	{
		id: 125,
		name: "Quattro Stagioni 23 cm",
		price: 39.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 126,
		name: "Quattro Stagioni 32 cm",
		price: 51.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 127,
		name: "Quattro Stagioni 42 cm",
		price: 65.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 128,
	// 	name: "Quattro Stagioni 60 cm",
	// 	price: 100.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 129,
		name: "Parma 23 cm",
		price: 40.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 130,
		name: "Parma 32 cm",
		price: 52.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 131,
		name: "Parma 42 cm",
		price: 67.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 132, name: "Parma 60 cm", price: 102.9, category: "Pizza", cm: 60 },
	{
		id: 133,
		name: "Roma 23 cm",
		price: 42.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 134,
		name: "Roma 32 cm",
		price: 54.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 135,
		name: "Roma 42 cm",
		price: 68.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 136, name: "Roma 60 cm", price: 104.9, category: "Pizza", cm: 60 },
	{
		id: 137,
		name: "Carbonara 23 cm",
		price: 36.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 138,
		name: "Carbonara 32 cm",
		price: 48.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 139,
		name: "Carbonara 42 cm",
		price: 62.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 140, name: "Carbonara 60 cm", price: 99.9, category: "Pizza", cm: 60 },
	{
		id: 141,
		name: "Verona 23 cm",
		price: 37.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 142,
		name: "Verona 32 cm",
		price: 49.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 143,
		name: "Verona 42 cm",
		price: 63.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 144, name: "Verona 60 cm", price: 98.9, category: "Pizza", cm: 60 },
	{
		id: 145,
		name: "Gyros 23 cm",
		price: 38.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 146,
		name: "Gyros 32 cm",
		price: 50.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 147,
		name: "Gyros 42 cm",
		price: 65.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 148, name: "Gyros 60 cm", price: 98.9, category: "Pizza", cm: 60 },
	{
		id: 149,
		name: "Leśny Skarb 23 cm",
		price: 39.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 150,
		name: "Leśny Skarb 32 cm",
		price: 51.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 151,
		name: "Leśny Skarb 42 cm",
		price: 65.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 152,
	// 	name: "Leśny Skarb 60 cm",
	// 	price: 100.9,
	// 	category: "Pizza",
	// 	cm: 60,
	// },
	{
		id: 153,
		name: "Barbecue 23 cm",
		price: 36.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 154,
		name: "Barbecue 32 cm",
		price: 48.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 155,
		name: "Barbecue 42 cm",
		price: 62.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// { id: 156, name: "Barbecue 60 cm", price: 95.9, category: "Pizza", cm: 42 },
	{
		id: 166,
		name: "Kompozycja własna 23 cm",
		price: 28.9,
		category: "Pizza",
		cm: 23,
		emoji: "🍕",
	},
	{
		id: 167,
		name: "Kompozycja własna 32 cm",
		price: 40.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},
	{
		id: 168,
		name: "Kompozycja własna 42 cm",
		price: 53.9,
		category: "Pizza",
		cm: 42,
		emoji: "🍕",
	},
	// {
	// 	id: 169,
	// 	name: "Kompozycja własna 60 cm",
	// 	price: 86.9,
	// 	category: "Pizza",
	// 	cm: 42,
	// },

	//PIZZA.........................................................................

	{
		id: 300,
		name: "Foccacia 32",
		price: 16.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},

	{
		id: 301,
		name: "WŁOSKIE PIECZYWO CZOSNKOWE 32",
		price: 21.9,
		category: "Pizza",
		cm: 32,
		emoji: "🍕",
	},

	{
		id: 230,
		name: "MISA FRYTEK Z KETCHUPEM",
		price: 17.9,
		category: "Makaron",
		emoji: "🍟",
	},

	{
		id: 165,
		name: "Deska Antipasti:",
		price: 79.9,
		category: "Makaron",
		emoji: "🧀🍖🍞",
	},

	{
		id: 160,
		name: "TALERZ KEBAB",
		price: 41.9,
		category: "Makaron",
		emoji: "🍖",
	},

	{ id: 161, name: "Sos czosnkowy:", price: 0, category: "sos", emoji: "🧴" },
	{ id: 162, name: "Sos Pomidorowy:", price: 0, category: "sos", emoji: "🧴" },
	{
		id: 227,
		name: "Sos Meksykanski (ostry):",
		price: 0,
		category: "sos",
		emoji: "🧴",
	},
	{ id: 163, name: "Sos czosnkowy:", price: 3.9, category: "sos", emoji: "🧴" },
	{
		id: 164,
		name: "Sos Pomidorowy:",
		price: 3.9,
		category: "sos",
		emoji: "🧴",
	},
	{
		id: 228,
		name: "Sos Meksykanski (ostry):",
		price: 3.9,
		category: "sos",
		emoji: "🧴",
	},
	//Sosy...............................................................................
	{
		id: 170,
		name: "Caldzone Capri:",
		price: 42.9,
		category: "pizza",
		emoji: "🥟",
	},
	{
		id: 171,
		name: "Caldzone Spinachi:",
		price: 47.9,
		category: "pizza",
		emoji: "🥟",
	},
	{
		id: 172,
		name: "Caldzone Extra:",
		price: 47.9,
		category: "pizza",
		emoji: "🥟",
	},
	{
		id: 173,
		name: "Caldzone Gyros:",
		price: 47.9,
		category: "pizza",
		emoji: "🥟",
	},
	//Caldzone.........................................................................
	{
		id: 174,
		name: "AGLIO OLIO",
		price: 34.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{ id: 175, name: "BOLOGNESE", price: 36.9, category: "Makaron", emoji: "🍝" },
	{ id: 176, name: "CARBONARA", price: 39.9, category: "Makaron", emoji: "🍝" },
	{ id: 177, name: "POLLO", price: 39.9, category: "Makaron", emoji: "🍝" },
	{ id: 178, name: "CALABRESE", price: 42.9, category: "Makaron", emoji: "🍝" },
	{ id: 179, name: "SPINACCI", price: 42.9, category: "Makaron", emoji: "🍝" },
	{
		id: 180,
		name: "FRUTTI DI MARE",
		price: 43.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{
		id: 181,
		name: "CON FUNGHI",
		price: 44.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{ id: 182, name: "INFERNO", price: 44.9, category: "Makaron", emoji: "🍝" },

	{ id: 183, name: "FORMAGGIO", price: 44.9, category: "Makaron", emoji: "🍝" },
	{
		id: 184,
		name: "GNOCCHI ZE SZPINAKIEM",
		price: 40.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{
		id: 185,
		name: "RAVIOLI Z ŁOSOSIEM",
		price: 44.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{
		id: 186,
		name: "RAVIOLI ALLE MELANZANE",
		price: 44.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{
		id: 187,
		name: "TORTELLINI RICOTTA E SPECK",
		price: 44.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{
		id: 268,
		name: "Tagliatelle VERDE del Mare",
		price: 44.9,
		category: "Makaron",
		emoji: "🍝",
	},
	{
		id: 317,
		name: "Tagliatelle Gambaretti",
		price: 45.9,
		category: "Makaron",
		emoji: "🍝",
	},
	//MAKARONY...........................................................................
	//SAŁATKI...................................
	{
		id: 263,
		name: "Sałatka  Grecka",
		price: 36.9,
		category: "sałatki",
		emoji: "🥗",
	},
	{
		id: 264,
		name: "Sałatka  z Kurczakiem",
		price: 39.9,
		category: "sałatki",
		emoji: "🥗",
	},
	{
		id: 265,
		name: "Sałatka  z Tuńczykiem",
		price: 39.9,
		category: "sałatki",
		emoji: "🥗",
	},
	{
		id: 266,
		name: "Sałatka  Parmeńska",
		price: 42.9,
		category: "sałatki",
		emoji: "🥗",
	},

	//SAŁATKI>>>>>>>>>>>........................................
	{
		id: 188,
		name: "Coca-Cola",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 189,
		name: "Coca-Cola 0%",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 190,
		name: "Fanta",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 191,
		name: "Sprite",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 192,
		name: "Kinley",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 193,
		name: "Kropla beskidu Gaz Woda",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 194,
		name: "Kropla beskidu NIE Gaz Woda",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 195,
		name: "Fuzetea Brzoskwiniowa",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 196,
		name: "Fuzetea Cytrynowa",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 197,
		name: "Cappy jabłkowy",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 198,
		name: "Cappy pomarańczowy",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 199,
		name: "Cappy multywitamina",
		price: 9.9,
		category: "Napój bezalkoholowy",
		emoji: "🥤",
	},
	{
		id: 200,
		name: "Lemoniada 0,4 L",
		price: 14.9,
		category: "Napój bezalkoholowy",
		emoji: "🍋🧊🌿",
	},
	{
		id: 201,
		name: "Lemoniada 1 L",
		price: 26.9,
		category: "Napój bezalkoholowy",
		emoji: "🍋🧊🌿",
	},
	{
		id: 202,
		name: "Dzban wody z cytryną i miętą 1 L",
		price: 16.9,
		category: "Napój bezalkoholowy",
		emoji: "🧊🌿",
	},
	{
		id: 302,
		name: "(Cola-cola 0.85 L)",
		price: 12.9,
		category: "Napój bezalkoholowy",
		emoji: "🧴🥤",
	},
	{
		id: 303,
		name: "(Fanta 0.85 L)",
		price: 12.9,
		category: "Napój bezalkoholowy",
		emoji: "🧴🥤",
	},
	{
		id: 304,
		name: "(Sprite 0.85 L)",
		price: 12.9,
		category: "Napój bezalkoholowy",
		emoji: "🧴🥤",
	},
	{
		id: 305,
		name: "(Cola-cola 0% 0.85 L)",
		price: 12.9,
		category: "Napój bezalkoholowy",
		emoji: "🧴🥤",
	},
	{
		id: 306,
		name: "(Sok jabłkowy 1 L)",
		price: 12.9,
		category: "Napój bezalkoholowy",
		emoji: "🧴🥤",
	},
	{
		id: 307,
		name: "(Sok pomarańczowy 1 L)",
		price: 12.9,
		category: "Napój bezalkoholowy",
		emoji: "🧴🥤",
	},
	{
		id: 203,
		name: "Świeżo wyciskany sok",
		price: 20.9,
		category: "Makaron",
		emoji: "🍊",
	},

	{ id: 205, name: "Herbata", price: 9.9, category: "Kawa", emoji: "🍵" },
	{ id: 206, name: "Espresso", price: 9.9, category: "Kawa", emoji: "☕" },
	{
		id: 207,
		name: "Kawa czarna",
		price: 10.9,
		category: "Kawa",
		emoji: "☕",
	},
	{
		id: 208,
		name: "Kawa czarna z mlekiem",
		price: 11.9,
		category: "Kawa",
		emoji: "☕",
	},
	{ id: 209, name: "Kawa Late", price: 12.9, category: "Kawa", emoji: "☕" },
	{ id: 210, name: "Cappucino", price: 12.9, category: "Kawa", emoji: "☕" },

	{
		id: 212,
		name: "Czekolada na gorąco",
		price: 12.9,
		category: "Kawa",
		emoji: "☕",
	},
	{
		id: 213,
		name: "Herbata zimowa",
		price: 16.9,
		category: "Kawa",
		emoji: "🍵",
	},
	//Napoje bezalkoholowe...............................................................................
	// {
	// 	id: 321,
	// 	name: "Lody domowe Romka Semifredo",
	// 	price: 26.9,
	// 	category: "Desery",
	// },
	{
		id: 214,
		name: "Puchar lodowy",
		price: 20.9,
		category: "Desery",
		emoji: "🍦",
	},
	{
		id: 215,
		name: "RizSzante Casa Burti Flute",
		price: 75,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 216,
		name: "Frizante Casa Burti Flute (Kieliszek)",
		price: 21,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 217,
		name: "Feudo Arancio Chardonnay",
		price: 90,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 218,
		name: "Feudo Arancio Chardonnay (Kieliszek)",
		price: 23,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{ id: 219, name: "Soave Domini Veneti", price: 110, category: "Wina" },
	{
		id: 220,
		name: "Soave Domini Veneti (Kieliszek)",
		price: 21,
		category: "Wina",
	},
	{
		id: 221,
		name: "Terre Cerere Montepulciano",
		price: 76,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 222,
		name: "Terre Cerere Montepulciano (Kieliszek)",
		price: 21,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 223,
		name: "Primitivo La Casada",
		price: 85,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 224,
		name: "Primitivo La Casada (Kieliszek)",
		price: 23,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 225,
		name: "Feudo Arancio Nero D`avola",
		price: 100,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 226,
		name: "Feudo Arancio Nero D`avola (Kieliszek)",
		price: 25,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 316,
		name: "Lepiga SoaveTenuta Santa Maria",
		price: 110,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 315,
		name: "Lepiga SoaveTenuta Santa Maria (Kieliszek)",
		price: 26,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 232,
		name: "Włoskie wino Domowe Karafka 0.5 l",
		price: 29.9,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 233,
		name: "Włoskie wino Domowe Karafka 0.25 l",
		price: 17.9,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 234,
		name: "Casa Lunardi SAN GIOVANNI (Czerwone)",
		price: 69.9,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 235,
		name: "Casa Lunardi SAN GIOVANNI (Białe)",
		price: 69.9,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 236,
		name: "Kieliszek wina domowego",
		price: 16.9,
		category: "Wina",
		emoji: "🍷🍇",
	},
	{
		id: 237,
		name: "Piwo z beczki 0.5",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 238,
		name: "Piwo z beczki 0.3",
		price: 10.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 239,
		name: "Piwo butelkowe z asortymentu",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 267,
		name: "Peroni 03 Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 318,
		name: "Książęce IPA Piwo ",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 269,
		name: "Książęce złote pszeniczne Piwo ",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 270,
		name: " Kozel Lezak Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 271,
		name: " Kozel Cerny Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 272,
		name: "Kapitan Jack Blue Piwo ",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 273,
		name: " Hardmade Yuzu Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 274,
		name: " Lech Free Lager 0% Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 275,
		name: "Lech Free Limonka z Miętą 0% Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 276,
		name: "Książęce złote pszeniczne 0% Piwo ",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 277,
		name: "Książęce IPA 0% Piwo",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 240,
		name: "Sok do piwa malina",
		price: 1.0,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 241,
		name: "Sok do piwa imbyr",
		price: 1.0,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 310,
		name: "Książęce Cherry Ale",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 311,
		name: "Książęce Czerwony Lager",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 312,
		name: "Książęce Porter",
		price: 15.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 319,
		name: "PIWO grzane",
		price: 19.9,
		category: "Piwo",
		emoji: "🍺",
	},
	{
		id: 320,
		name: "WINO grzane",
		price: 19.9,
		category: "Piwo",
		emoji: "🍷🍇",
	},
	// BAR>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	// { id: 242, name: "Sałatka z Kozim serem", price: 45.0, category: "sałatki" },
	// { id: 243, name: "Sałatka Caprese", price: 34.9, category: "sałatki" },
	// { id: 244, name: "Makaron Pesto", price: 41.9, category: "makaron" },
	// {
	// 	id: 245,
	// 	name: "Makaron Pollo e Spinaci",
	// 	price: 44.9,
	// 	category: "makaron",
	// emoji: "🍝",
	// },
	// { id: 246, name: "Pizza Pesto", price: 44.9, category: "pizza" },
	// {
	// 	id: 314,
	// 	name: "Deska Antipasti dla 1 osoby",
	// 	price: 34.9,
	// 	category: "makaron",
	// },
	// { id: 247, name: "Pizza Mortadella", price: 45.9, category: "pizza" },
	// { id: 248, name: "Pizza Pollo e spinaci", price: 46.9, category: "pizza" },

	{
		id: 250,
		name: "Czerwony Szprycer",
		price: 29.9,
		category: "Drinki",
		emoji: "🍹",
	},
	{
		id: 251,
		name: "Zielony Szprycer",
		price: 29.9,
		category: "Drinki",
		emoji: "🍹",
	},
	{
		id: 252,
		name: "Sycylijski zachód słońca",
		price: 29.9,
		category: "Drinki",
		emoji: "🍹",
	},
	{ id: 253, name: "Hugo", price: 29.9, category: "Drinki", emoji: "🍹" },
	{
		id: 254,
		name: "Martini Fiero",
		price: 29.9,
		category: "Drinki",
		emoji: "🍹",
	},
	{
		id: 255,
		name: "Martini bianko",
		price: 29.9,
		category: "Drinki",
		emoji: "🍹",
	},
	{ id: 256, name: "Klasyczna kawa mrożona", price: 14.9, category: "Kawa" },
	// { id: 257, name: "Kokosowa kawa mrożona", price: 16.9, category: "Kawa" },
	// { id: 258, name: "Karmelowa kawa mrożona", price: 16.9, category: "Kawa" },
	// { id: 259, name: "Orzechowa kawa mrożona", price: 16.9, category: "Kawa" },
	// { id: 260, name: "Lody domowe Semifredo", price: 19.9, category: "Kawa" },
	// {
	// 	id: 261,
	// 	name: "Lemoniada Kwiatkowa Magiczna 0.4 L",
	// 	price: 14.9,
	// 	category: "Napój bezalkoholowy",
	// },
	// {
	// 	id: 262,
	// 	name: "Lemoniada Kwiatkowa Magiczna 1 L",
	// 	price: 26.9,
	// 	category: "Napój bezalkoholowy",
	// },
	// {
	// 	id: 278,
	// 	name: "Mus czekoladowy, Krem czekoladowy",
	// 	price: 19.9,
	// 	category: "Desery",
	// },
	// {
	// 	id: 309,
	// 	name: "MINESTRONE Krem zupa sezonowa minestrone",
	// 	price: 24.9,
	// 	category: "sałatki",
	// },
	{
		id: 338,
		name: "POMIDOROWA Krem zupa sezonowa z pomidorów",
		price: 24.9,
		category: "sałatki",
		emoji: "🍲",
	},
	// { id: 322, name: "Verdure Gigliate", price: 39.9, category: "sałatki" },
	// {
	// 	id: 323,
	// 	name: "Zielone i czarne oliwki ",
	// 	price: 19.9,
	// 	category: "sałatki",
	// },
	// {
	// 	id: 324,
	// 	name: "Cappellacci z kurkami w sosie rozmarynowym",
	// 	price: 46.9,
	// 	category: "sałatki",
	// },
	// {
	// 	id: 325,
	// 	name: "Taglitelle alle zucchine",
	// 	price: 42.9,
	// 	category: "sałatki",
	// },
	// { id: 326, name: "Taglitelle ai finferi", price: 44.9, category: "sałatki" },
	// { id: 327, name: "Taglitelle al salmone", price: 45.9, category: "sałatki" },
	// { id: 328, name: "Pepe", price: 46.9, category: "pizza" },
	// { id: 329, name: "Pera", price: 47.9, category: "pizza" },
	// { id: 330, name: "Finferli", price: 49.9, category: "pizza" },
	{
		id: 331,
		name: "Tiramisu",
		price: 24.9,
		category: "Desery",
	},
	{
		id: 332,
		name: "Ciastko bezowe ",
		price: 26.9,
		category: "Desery",
	},
	{
		id: 333,
		name: "Penne Napoli (DLA DZIECI 130 makaronu)",
		price: 25.9,
		category: "Desery",
		emoji: "🍝",
	},
	{
		id: 334,
		name: "Spaghetti Bolognese (DLA DZIECI 130 makaronu) ",
		price: 27.9,
		category: "Desery",
		emoji: "🍝",
	},
	{
		id: 335,
		name: "MINI pizza MARGHARITA",
		price: 25.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 336,
		name: "MINI pizza PROSCIUTTO",
		price: 28.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 337,
		name: "MINI pizza HAWAJSKA",
		price: 29.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 339,
		name: "Ciasto na pizze Kulka",
		price: 6.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 340,
		name: "Promocja LUTY WYPAS PIZZA do syta",
		price: 39.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 341,
		name: "Promocja LUTY PIJ ILE CHCESZ wielka dolewka",
		price: 14.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 342,
		name: "Promosja LUTY PIJ I JEDZ ILE CHCESZ Pzza + Dolewka",
		price: 49.9,
		category: "pizza",
		emoji: "🍕",
	},
	{ id: 343, name: "Promocja Lutty PIZZA ", price: 0.0, category: "pizza" },
	// {
	// 	id: 344,
	// 	name: "Tagliatelle Pollo e Arancia ",
	// 	price: 43.0,
	// 	category: "makaron",
	// emoji: "🍝",
	// },
	// {
	// 	id: 345,
	// 	name: "Polędwica wołowa San Giovanni ",
	// 	price: 59.0,
	// 	category: "makaron",
	// },
	// { id: 346, name: "Pizza Sardegna  ", price: 48.0, category: "pizza" },
	{ id: 347, name: "Tarta cytrynowa  ", price: 21.0, category: "Desery" },
	{
		id: 348,
		name: "Queasidilla Fuego Loco (chorizo, cebula)  ",
		price: 42.9,
		category: "makaron",
	},
	{
		id: 349,
		name: "el Frita del Carnita (frytki z bolkiem)  ",
		price: 29.9,
		category: "makaron",
	},
	{
		id: 350,
		name: "Batata Frita Chorizo (babat z chorizo) ",
		price: 29.9,
		category: "makaron",
	},
	{
		id: 351,
		name: " Zupa krem z dyni  ",
		price: 19.9,
		category: "makaron",
		emoji: "🍲",
	},
	{
		id: 352,
		name: "Zupa krem z kurek ( z grzankami)",
		price: 25.9,
		category: "makaron",
		emoji: "🍲",
	},
	{
		id: 353,
		name: " Pizza Finferli (kurki, boczek, cebula)  ",
		price: 49.9,
		category: "pizza",
		emoji: "🍕",
	},
	{
		id: 354,
		name: "Pasta Zucca Piccante   ",
		price: 43.9,
		category: "makaron",
	},
	{
		id: 355,
		name: "Aperol Spritz (100 proseko, 75 aperolu, 50 ml woda gaz) ",
		price: 30.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 356,
		name: "Hugo Spritz (150 proseko, 30 ml syropu z czarnego bzu, 100 ml woda gaz) ",
		price: 30.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 357,
		name: "Martini (W Shaker lód , 80 ml ginu, 40 ml martini, mieszamy i przelewamy  zielona oliwka)  ",
		price: 30.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 358,
		name: "Sex on the beach (40 ml wódki, 20 ml likieru brzoskwiniowego, 40 ml soku pomarańczowego, 40 ml soku żurawinowego, pół szklanki lodu i tam sok żurawinowy, a do shakiera wszysto inne,  i póżniej do szklanki ) ",
		price: 32.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 359,
		name: "Tequila Sunrise (40 ml tequili, 90 ml soku pomarańczowego, 15 ml grenadyny, pół szklanki lodu, do shakiera tequilę i sok pomarańczowy, a do szklanki lód i grenadynę)  ",
		price: 32.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 360,
		name: "Whisky Sour (60 ml whisky, 30 ml soku z cytryny, 15 ml syropu cukrowego, 1 białko,  pół szklanki lodu, do shakiera wszystko i przelewamy do szklanki)  ",
		price: 32.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 361,
		name: "Mohito (45 ml białego rumu, 20 ml soku z limonki,  mięta, woda gazowana, pół szklanki lodu, wszystko do szklanki i utłucz)  ",
		price: 32.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 362,
		name: "Limoncello Spritz (90 ml proseko, 60 ml limoncello, 30 ml woda gaz, lód, i wszystko mieszamy)  ",
		price: 32.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 363,
		name: "Negroni (40 ml ginu, 40 ml campari, 40 ml martini rosso, lód i pomarańcza do dekoracji, wszystko mieszamy w szklance)  ",
		price: 32.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 364,
		name: "Gin Tonic (50 ml ginu, 150 ml toniku, lód i cytryna do dekoracji, wszystko mieszamy w szklance)  ",
		price: 30.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 365,
		name: "Mohito bezalkoholowe ( limonka, mięta, cukier tr. woga gaz, Sprite)  ",
		price: 25.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 366,
		name: "Margarita bezalkoholowa ( Truskawki, syrop truskawkowy, woga gaz, Sprite)  ",
		price: 25.0,
		category: "Wina",
		emoji: "🍹",
	},
	{
		id: 367,
		name: "Wódka Żubrówka czarbna ( 0.4 ML !!) ",
		price: 12.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 368,
		name: "Wódka Żubrówka czarbna ( 0.5 L !!)  ",
		price: 150.0,
		category: "Wina",
		emoji: "🍾",
	},
	{
		id: 369,
		name: "Wódka wyborowa (0.4 ML !!)  ",
		price: 11.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 370,
		name: "Wódka wyborowa (0.5 L !!)   ",
		price: 140.0,
		category: "Wina",
		emoji: "🍾",
	},
	{
		id: 371,
		name: "Wódka Stumbras (0.4 ML !!)   ",
		price: 13.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 372,
		name: "Wódka Stumbras (0.5 L !!)  ",
		price: 165.0,
		category: "Wina",
		emoji: "🍾",
	},
	{
		id: 373,
		name: "Whisky Johnnie Walker (0.4 ML !!)  ",
		price: 13.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 374,
		name: "Whisky Johnnie Walker  (0.7 L !!)  ",
		price: 210.0,
		category: "Wina",
		emoji: "🍾",
	},
	{
		id: 375,
		name: "Wchisky Jack Daniel's (0.4 ML !!)  ",
		price: 18.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 376,
		name: "Wchisky Jack Daniel's(0.7 L !!)  ",
		price: 210.0,
		category: "Wina",
		emoji: "🍾",
	},
	{
		id: 377,
		name: "Whisky Bulleit Burton (0.4 ML !!)  ",
		price: 21.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 378,
		name: "Whisky Bulleit Burton (0.7 L !!)  ",
		price: 299.0,
		category: "Wina",
		emoji: "🍾",
	},
	{
		id: 379,
		name: "Tequila Sierra Silver(0.4 ML !!)  ",
		price: 15.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 380,
		name: "Tequilla Sierra Reposado Gold(0.4 ML !!)  ",
		price: 15.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 381,
		name: "Rum Bacardi Carta Blanca (0.4 ML !!)  ",
		price: 12.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 382,
		name: "Rum Bacardi Carta Negra (0.4 ML !!)  ",
		price: 12.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 383,
		name: "Gin Bombay Saphire(0.4 ML !!)  ",
		price: 18.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 384,
		name: "Gin Malfy (0.4 ML !!)  ",
		price: 16.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 385,
		name: "Likier Limoncello (0.4 ML !!)  ",
		price: 18.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 386,
		name: "Likier Campari Bitter (0.4 ML !!)  ",
		price: 18.0,
		category: "Wina",
		emoji: "🥛",
	},
	{
		id: 387,
		name: "Dostawa minimum 40 zł, koszt 5  ",
		price: 5.0,
		category: "pizza",
		emoji: "🛵",
	},
	{
		id: 388,
		name: "+ Opakowanie Karton Pudelko do każdej pozycji poza sosem 2 zł ",
		price: 2.0,
		category: "pizza",
		emoji: "📦🍕",
	},
	{
		id: 389,
		name: "Ogórkowa zupa",
		price: 14.9,
		category: "makaron",
		emoji: "🍲",
	},
];
// id 390 start
